[package]
name = "site"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[dependencies]
maud.workspace = true
grass.workspace = true

log.workspace = true

serde = { workspace = true, features = ["derive"] }
wasm-bindgen.workspace = true
js-sys.workspace = true
web-sys = { workspace = true, features = ["DedicatedWorkerGlobalScope", "MessageEvent", "Request", "RequestInit", "RequestMode", "Response", "WorkerLocation"] }
tokio = { version = "1", features = ["sync"] }
wasm-bindgen-futures = "0.4"

common = { path = '../common/' }
wasm_bridge = { path = '../wasm_bridge/' }
lol_alloc = "0.4.1"

rand.workspace = true
getrandom = { version = "0.3", features = ["wasm_js"] }

[features]
hot-reload = ["wasm_bridge/hot-reload"]
