[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44", features = ["rt", "rt-multi-thread", "net", "sync"] }
axum = { version = "0.8", default-features = false, features = ["http1", "tokio", "query", "json", "ws"] }
wasmtime = "40"
notify = "8"
tower-http = { version = "0.6", features = ["fs", "compression-br", "compression-deflate", "compression-gzip", "compression-zstd", "cors"] }

maud = { workspace = true, features = ["axum"] }

image.workspace = true
serde.workspace = true

common = { path = '../common/' }

thiserror.workspace = true
anyhow.workspace = true

log.workspace = true
colog = "1"
