[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44", features = ["rt", "rt-multi-thread", "net", "sync"] }
# futures = "0.3"
rayon = "1"

axum = { version = "0.8", default-features = false, features = ["http1", "tokio", "query", "json", "ws"] }
tower-http = { version = "0.6", features = ["fs", "compression-br", "compression-deflate", "compression-gzip", "compression-zstd", "cors"] }

wasmtime = "41"

notify = "8"
notify-debouncer-mini = "0.7.0"
walkdir = "2"

maud = { workspace = true, features = ["axum"] }
lol_html = "2.7.1"

image = {workspace = true, default-features = true }
fast_image_resize = { version = "6", features = ["image", "rayon"] }
webp= "0.3"

common = { path = '../common/' }

thiserror.workspace = true
anyhow.workspace = true

log.workspace = true
# colog = "1"
env_logger = "0.11"

serde.workspace = true
serde_json = "1"

# base64.workspace = true
uuid.workspace = true

rand.workspace = true

lofty = "0.22"

sqlx = { version = "0.8", default-features = false, features = [ "runtime-tokio", "sqlite", "derive", "migrate", "macros", "uuid" ] }
