[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25", default-features = false }
maud = { version = "0.27" }
rand = { version = "0.9" , default-features = false, features = ["std", "thread_rng"]}
serde = { version = "1", features = ["derive"] }

macros = { path = "../macros/" }
base64 = "0.22.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

