[package]
name = "wasm_bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true

maud.workspace = true

wasm-bindgen.workspace = true
js-sys.workspace = true
console_error_panic_hook.workspace = true
web-sys = { workspace = true, features = [
    "Window", 

    "Document", 
    "HtmlDocument",

    "Element", 
    "HtmlElement",
    "HtmlStyleElement",
    "HtmlHeadElement",

    "CssStyleDeclaration",

    "DomTokenList",
    "DomRect",

    "NodeList",

    "Location",
    "Url",

    "WebSocket", 
    "MessageEvent",
    "CloseEvent",
    "ErrorEvent",

    "WheelEvent",

    "Worker",
    "WorkerOptions",
    "Blob",
    "BlobPropertyBag",

    "console",
] }

[features]
hot-reload = []

